### ISSUE TITLE
Add a picture

### ISSUE THREAD

**Issue by dgurnani12** [dgurnani12/dgurnani12.github.io#5]
add a picture from anywhere

**Comment by kippllo** [comment]
What exactly do you mean? Do you just want us to put a picture in?

**Comment by dgurnani12** [comment]
@kippllo yes

**Comment by kippllo** [comment]
Is this even a real project?? XD

**Comment by dgurnani12** [comment]
@kippllo I just fixed this issue... thanks for your help
